// DOM element cache - populated once on load
export const dom = {
    sidebar:              document.getElementById('sidebar'),
    board:                document.getElementById('game-board'),
    timerDisplay:         document.getElementById('timer-display'),
    startBtn:             document.getElementById('start-btn'),
    checkBtn:             document.getElementById('check-btn'),
    menuBtn:              document.getElementById('menu-btn'),
    shareBtn:             document.getElementById('share-btn'),
    resultDisplay:        document.getElementById('result'),
    feedbackContainer:    document.getElementById('feedback-container'),
    btnLike:              document.getElementById('btn-like'),
    btnDislike:           document.getElementById('btn-dislike'),
    btnSkip:              document.getElementById('btn-skip'),
    levelTitle:           document.getElementById('level-title'),
    dayButtonsContainer:  document.getElementById('day-buttons-container'),
    playerNameMainInput:  document.getElementById('player-name-main'),
    verifyNameBtn:        document.getElementById('verify-name-btn'),
    nameStatus:           document.getElementById('name-status'),
    nameInputContainer:   document.getElementById('name-input-container'),
    lockedNameDisplay:    document.getElementById('locked-name-display'),
    leaderboardSection:   document.getElementById('leaderboard-section'),
    dbMessage:            document.getElementById('db-message'),
    leaderboardList:      document.getElementById('leaderboard-list'),
    leaderboardTitle:     document.getElementById('leaderboard-title'),
};
